services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/my-next-app:cached
      - pnpm-store:/home/node/.local/share/pnpm/store
    command: sleep infinity
    env_file:
      - ${PWD}/.env.local
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - ${PWD}/.env.local
    environment:
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD',
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    env_file:
      - ${PWD}/.env.local
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data

volumes:
  mysql-data:
  redis-data:
  minio-data:
  pnpm-store:
